sudo: false
language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
    - bower_components
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm run build
  - npm run semantic-release
branches:
  except:
    # Ignore Git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
