sudo: false
language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm prune
after_success:
  - npm run build
  - npm run semantic-release
